### ISSUE TITLE
Error: `make` failed with exit code: 2

### ISSUE THREAD

**Issue by Trenrod** [JoshKaufman/ursa#163]
Fresh installed Ubuntu 16.04.3 LTS via Vagrant

Executes to reproduce:
cd /home/ubuntu
sudo apt-get search node
sudo apt-cache search node
curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
sudo apt-get install -y nodejs
sudo apt-get install -y build-essential

makedir tests
cd tests

npm init
// Just for test -> works
sudo npm install -g node-gyp
// Just for test -> works
sudo npm install --save ursa

```
ubuntu@ubuntu-xenial:~/tests$ sudo npm install chef-api --save

> ursa@0.9.1 install /home/ubuntu/tests/node_modules/chef-api/node_modules/ursa
> node-gyp rebuild

make: Entering directory '/home/ubuntu/tests/node_modules/chef-api/node_modules/ursa/build'
  CXX(target) Release/obj.target/ursaNative/src/ursaNative.o
In file included from ../node_modules/nan/nan.h:194:0,
                 from ../src/ursaNative.h:10,
                 from ../src/ursaNative.cc:3:
../node_modules/nan/nan_maybe_43_inl.h: In function ‘Nan::MaybeLocal<v8::Object> Nan::CloneElementAt(v8::Local<v8::Array>, uint32_t)’:
../node_modules/nan/nan_maybe_43_inl.h:221:58: warning: ‘v8::MaybeLocal<v8::Object> v8::Array::CloneElementAt(v8::Local<v8::Context>, uint32_t)’ is deprecated: Cloning is not supported. [-Wdeprecated-declarations]
   return array->CloneElementAt(GetCurrentContext(), index);
                                                          ^
In file included from /home/ubuntu/.node-gyp/6.11.5/include/node/v8.h:25:0,
                 from /home/ubuntu/.node-gyp/6.11.5/include/node/node.h:42,
                 from ../src/ursaNative.h:9,
                 from ../src/ursaNative.cc:3:
/home/ubuntu/.node-gyp/6.11.5/include/node/v8.h:3032:36: note: declared here
                 MaybeLocal<Object> CloneElementAt(Local<Context> context,
                                    ^
/home/ubuntu/.node-gyp/6.11.5/include/node/v8config.h:333:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
In file included from ../node_modules/nan/nan_new.h:189:0,
                 from ../node_modules/nan/nan.h:200,
                 from ../src/ursaNative.h:10,
                 from ../src/ursaNative.cc:3:
../node_modules/nan/nan_implementation_12_inl.h: In static member function ‘static Nan::imp::FactoryBase<v8::BooleanObject>::return_t Nan::imp::Factory<v8::BooleanObject>::New(bool)’:
../node_modules/nan/nan_implementation_12_inl.h:40:38: warning: ‘static v8::Local<v8::Value> v8::BooleanObject::New(bool)’ is deprecated: Pass an isolate [-Wdeprecated-declarations]
   return v8::BooleanObject::New(value).As<v8::BooleanObject>();
                                      ^
In file included from /home/ubuntu/.node-gyp/6.11.5/include/node/v8.h:25:0,
                 from /home/ubuntu/.node-gyp/6.11.5/include/node/node.h:42,
                 from ../src/ursaNative.h:9,
                 from ../src/ursaNative.cc:3:
/home/ubuntu/.node-gyp/6.11.5/include/node/v8.h:4009:56: note: declared here
   V8_DEPRECATED("Pass an isolate", static Local<Value> New(bool value));
                                                        ^
/home/ubuntu/.node-gyp/6.11.5/include/node/v8config.h:333:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
In file included from ../src/ursaNative.h:10:0,
                 from ../src/ursaNative.cc:3:
../node_modules/nan/nan.h: At global scope:
../node_modules/nan/nan.h:602:20: error: variable or field ‘AddGCEpilogueCallback’ declared void
       v8::Isolate::GCEpilogueCallback callback
                    ^
../node_modules/nan/nan.h:602:7: error: ‘GCEpilogueCallback’ is not a member of ‘v8::Isolate’
       v8::Isolate::GCEpilogueCallback callback
       ^
../node_modules/nan/nan.h:603:18: error: expected primary-expression before ‘gc_type_filter’
     , v8::GCType gc_type_filter = v8::kGCTypeAll) {
                  ^
../node_modules/nan/nan.h:608:20: error: variable or field ‘RemoveGCEpilogueCallback’ declared void
       v8::Isolate::GCEpilogueCallback callback) {
                    ^
../node_modules/nan/nan.h:608:7: error: ‘GCEpilogueCallback’ is not a member of ‘v8::Isolate’
       v8::Isolate::GCEpilogueCallback callback) {
       ^
../node_modules/nan/nan.h:613:20: error: variable or field ‘AddGCPrologueCallback’ declared void
       v8::Isolate::GCPrologueCallback callback
                    ^
../node_modules/nan/nan.h:613:7: error: ‘GCPrologueCallback’ is not a member of ‘v8::Isolate’
       v8::Isolate::GCPrologueCallback callback
       ^
../node_modules/nan/nan.h:614:18: error: expected primary-expression before ‘gc_type_filter’
     , v8::GCType gc_type_filter = v8::kGCTypeAll) {
                  ^
../node_modules/nan/nan.h:619:20: error: variable or field ‘RemoveGCPrologueCallback’ declared void
       v8::Isolate::GCPrologueCallback callback) {
                    ^
../node_modules/nan/nan.h:619:7: error: ‘GCPrologueCallback’ is not a member of ‘v8::Isolate’
       v8::Isolate::GCPrologueCallback callback) {
       ^
../node_modules/nan/nan.h: In function ‘bool Nan::SetAccessor(v8::Local<v8::Object>, v8::Local<v8::String>, Nan::GetterCallback, Nan::SetterCallback, v8::Local<v8::Value>, v8::AccessControl, v8::PropertyAttribute)’:
../node_modules/nan/nan.h:1961:16: warning: ‘bool v8::Object::SetAccessor(v8::Local<v8::Name>, v8::AccessorNameGetterCallback, v8::AccessorNameSetterCallback, v8::Local<v8::Value>, v8::AccessControl, v8::PropertyAttribute)’ is deprecated: Use maybe version [-Wd
eprecated-declarations]
     , attribute);
                ^
In file included from /home/ubuntu/.node-gyp/6.11.5/include/node/v8.h:25:0,
                 from /home/ubuntu/.node-gyp/6.11.5/include/node/node.h:42,
                 from ../src/ursaNative.h:9,
                 from ../src/ursaNative.cc:3:
/home/ubuntu/.node-gyp/6.11.5/include/node/v8.h:2751:22: note: declared here
                 bool SetAccessor(Local<Name> name,
                      ^
/home/ubuntu/.node-gyp/6.11.5/include/node/v8config.h:333:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
ursaNative.target.mk:97: recipe for target 'Release/obj.target/ursaNative/src/ursaNative.o' failed
make: *** [Release/obj.target/ursaNative/src/ursaNative.o] Error 1
make: Leaving directory '/home/ubuntu/tests/node_modules/chef-api/node_modules/ursa/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)
gyp ERR! System Linux 4.4.0-93-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/ubuntu/tests/node_modules/chef-api/node_modules/ursa
gyp ERR! node -v v6.11.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
chefserverutils@1.0.0 /home/ubuntu/tests
└── (empty)

npm WARN chefserverutils@1.0.0 No repository field.
npm ERR! Linux 4.4.0-93-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "chef-api" "--save"
npm ERR! node v6.11.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! ursa@0.9.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ursa@0.9.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ursa package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ursa
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ursa
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/tests/npm-debug.log
npm ERR! code 1
```

**Comment by Trenrod** [comment]
Sorry wrong repo :(
