### ISSUE TITLE
nodejs 10.0.0 build failed

### ISSUE THREAD

**Issue by jinceon** [JoshKaufman/ursa#167]
macos 10.13.4
node 10.0.0
```

> ursa@0.9.4 install /Users/gaojinceon/WebstormProjects/dianziyan/node_modules/ursa
> node-gyp rebuild

  CXX(target) Release/obj.target/ursaNative/src/ursaNative.o
../src/ursaNative.cc:389:13: error: member access into incomplete type 'RSA' (aka 'rsa_st')
    obj->rsa->n = BN_bin2bn(data_n, n_length, NULL);
            ^
/Users/gaojinceon/.node-gyp/10.0.0/include/node/openssl/ossl_typ.h:110:16: note: forward declaration of 'rsa_st'
typedef struct rsa_st RSA;
               ^
../src/ursaNative.cc:390:13: error: member access into incomplete type 'RSA' (aka 'rsa_st')
    obj->rsa->e = BN_bin2bn(data_e, e_length, NULL);
            ^
/Users/gaojinceon/.node-gyp/10.0.0/include/node/openssl/ossl_typ.h:110:16: note: forward declaration of 'rsa_st'
typedef struct rsa_st RSA;
               ^
../src/ursaNative.cc:407:35: error: member access into incomplete type 'RSA' (aka 'rsa_st')
    if ((obj == NULL) || (obj->rsa->d != NULL)) {
                                  ^
/Users/gaojinceon/.node-gyp/10.0.0/include/node/openssl/ossl_typ.h:110:16: note: forward declaration of 'rsa_st'
typedef struct rsa_st RSA;
               ^
../src/ursaNative.cc:536:34: error: member access into incomplete type 'RSA' (aka 'rsa_st')
    bignumToBuffer(args, obj->rsa->e);
                                 ^
/Users/gaojinceon/.node-gyp/10.0.0/include/node/openssl/ossl_typ.h:110:16: note: forward declaration of 'rsa_st'
typedef struct rsa_st RSA;
               ^
../src/ursaNative.cc:552:34: error: member access into incomplete type 'RSA' (aka 'rsa_st')
    bignumToBuffer(args, obj->rsa->d);
                                 ^
/Users/gaojinceon/.node-gyp/10.0.0/include/node/openssl/ossl_typ.h:110:16: note: forward declaration of 'rsa_st'
typedef struct rsa_st RSA;
               ^
../src/ursaNative.cc:567:34: error: member access into incomplete type 'RSA' (aka 'rsa_st')
    bignumToBuffer(args, obj->rsa->n);
                                 ^
/Users/gaojinceon/.node-gyp/10.0.0/include/node/openssl/ossl_typ.h:110:16: note: forward declaration of 'rsa_st'
typedef struct rsa_st RSA;
               ^
../src/ursaNative.cc:1218:17: error: member access into incomplete type 'RSA' (aka 'rsa_st')
        obj->rsa->n = modulus;
                ^
/Users/gaojinceon/.node-gyp/10.0.0/include/node/openssl/ossl_typ.h:110:16: note: forward declaration of 'rsa_st'
typedef struct rsa_st RSA;
               ^
../src/ursaNative.cc:1219:17: error: member access into incomplete type 'RSA' (aka 'rsa_st')
        obj->rsa->e = exponent;
                ^
/Users/gaojinceon/.node-gyp/10.0.0/include/node/openssl/ossl_typ.h:110:16: note: forward declaration of 'rsa_st'
typedef struct rsa_st RSA;
               ^
../src/ursaNative.cc:1220:17: error: member access into incomplete type 'RSA' (aka 'rsa_st')
        obj->rsa->p = p;
                ^
/Users/gaojinceon/.node-gyp/10.0.0/include/node/openssl/ossl_typ.h:110:16: note: forward declaration of 'rsa_st'
typedef struct rsa_st RSA;
               ^
../src/ursaNative.cc:1221:17: error: member access into incomplete type 'RSA' (aka 'rsa_st')
        obj->rsa->q = q;
                ^
/Users/gaojinceon/.node-gyp/10.0.0/include/node/openssl/ossl_typ.h:110:16: note: forward declaration of 'rsa_st'
typedef struct rsa_st RSA;
               ^
../src/ursaNative.cc:1222:17: error: member access into incomplete type 'RSA' (aka 'rsa_st')
        obj->rsa->dmp1 = dp;
                ^
/Users/gaojinceon/.node-gyp/10.0.0/include/node/openssl/ossl_typ.h:110:16: note: forward declaration of 'rsa_st'
typedef struct rsa_st RSA;
               ^
../src/ursaNative.cc:1223:17: error: member access into incomplete type 'RSA' (aka 'rsa_st')
        obj->rsa->dmq1 = dq;
                ^
/Users/gaojinceon/.node-gyp/10.0.0/include/node/openssl/ossl_typ.h:110:16: note: forward declaration of 'rsa_st'
typedef struct rsa_st RSA;
               ^
../src/ursaNative.cc:1224:17: error: member access into incomplete type 'RSA' (aka 'rsa_st')
        obj->rsa->iqmp = inverseQ;
                ^
/Users/gaojinceon/.node-gyp/10.0.0/include/node/openssl/ossl_typ.h:110:16: note: forward declaration of 'rsa_st'
typedef struct rsa_st RSA;
               ^
../src/ursaNative.cc:1225:17: error: member access into incomplete type 'RSA' (aka 'rsa_st')
        obj->rsa->d = d;
                ^
/Users/gaojinceon/.node-gyp/10.0.0/include/node/openssl/ossl_typ.h:110:16: note: forward declaration of 'rsa_st'
typedef struct rsa_st RSA;
               ^
../src/ursaNative.cc:1270:17: error: member access into incomplete type 'RSA' (aka 'rsa_st')
        obj->rsa->n = modulus;
                ^
/Users/gaojinceon/.node-gyp/10.0.0/include/node/openssl/ossl_typ.h:110:16: note: forward declaration of 'rsa_st'
typedef struct rsa_st RSA;
               ^
../src/ursaNative.cc:1271:17: error: member access into incomplete type 'RSA' (aka 'rsa_st')
        obj->rsa->e = exponent;
                ^
/Users/gaojinceon/.node-gyp/10.0.0/include/node/openssl/ossl_typ.h:110:16: note: forward declaration of 'rsa_st'
typedef struct rsa_st RSA;
               ^
16 errors generated.
make: *** [Release/obj.target/ursaNative/src/ursaNative.o] Error 1

```

**Comment by hsalokor** [comment]
I'm seeing this too

**Comment by shmoop207** [comment]
+1

**Comment by uditalias** [comment]
+1

**Comment by coolaj86** [comment]
Fixed by using node v8.x :trollface: 

(I also had problems with v9.x for entirely different reasons, so I don't suggest that either)

## Update: Node v10+ has Native RSA Support now

* `crypto.generateKeyPair()` 
  * https://nodejs.org/api/crypto.html#crypto_crypto_generatekeypair_type_options_callback
* `Rasha.generate()` (RSA + PEM<->JWK)
  * https://git.coolaj86.com/coolaj86/keypairs.js/
* `Keypairs.generate()` (RSA/ECDSA + PEM<->JWK)
  * https://git.coolaj86.com/coolaj86/rasha.js/

**Comment by coolaj86** [comment]
In all seriousness though:

I just got a bug report in greenlock.js about this the other day.

My workaround for times like these (as they do happen from time-to-time between major releases or testing code on a new CPU platform and such) is that I created [rsa-compat.js](https://git.coolaj86.com/coolaj86/rsa-compat.js) as a wrapper around both forge.js and ursa.js so that even if it's degraded performance (i.e. pure JS only) I always have working code.

I just wanted to mention that in case anyone else's use case is limited to the same set of features that forge also supports you can use both in the interim.

**Comment by jkuri** [comment]
https://github.com/JoshKaufman/ursa/pull/169 fixes this issue.

**Comment by postal286** [comment]
Which node v builds ursa fine ? Have the same issue with node 8.9.0 / docker / carbon image

**Comment by raideltorres** [comment]
I solved this using node v8 but I was facing this issue with node v10

**Comment by danwdart** [comment]
Once you merge the patch to deal with Node 10, then this should be closed. Until then, it's not fixed, right? For most downgrading is not an option.

**Comment by syzer** [comment]
:+1:

**Comment by igmsantos** [comment]
I've tested the patch and this works fine, please merge the fix to enable us to upgrade the nodeJS or maybe fork the project for another one who'll do the merge.

**Comment by bobiscool** [comment]
aha

**Comment by rzr** [comment]
Please also release package on npm,
if not yet done

**Comment by coolaj86** [comment]
I've loved uRSA and I'm so glad it's been around this long time, however, it is no longer necessary for generating keypair PEMs and DERs (which I think is its primary use case) in node v10 and higher:

* https://coolaj86.com/articles/new-in-node-native-rsa-ec-and-dsa-support/
* https://nodejs.org/api/crypto.html#crypto_crypto_generatekeypair_type_options_callback

If you have a use case that is solved by uRSA and isn't solved by the new node APIs, I'd love to hear about it so I can think on it (and perhaps go back and poke at the issue and encourage the node devs to include it).

That said, I still haven't migrated all of my code that uses it away from it, but I'm pretty confident that now I can.

## Update: Node v10+ has Native RSA Support now

* `crypto.generateKeyPair()` 
  * https://nodejs.org/api/crypto.html#crypto_crypto_generatekeypair_type_options_callback
* `Rasha.generate()` (RSA + PEM<->JWK)
  * https://git.coolaj86.com/coolaj86/keypairs.js/
* `Keypairs.generate()` (RSA/ECDSA + PEM<->JWK)
  * https://git.coolaj86.com/coolaj86/rasha.js/

**Comment by delfuego** [comment]
I think the issue is that while Node 10 is the new LTS, it's still not yet standard in actual use — mostly because there are still a bunch of heavy-use modules that haven't been upgraded to be compatible with Node 10. I certainly know I have a project that uses Ursa that I can't yet upgrade to Node 10... meaning I'm stuck at Node 8, and very much need Ursa.

**Comment by delfuego** [comment]
(Also, I don't think I'd say that the major use case of Ursa is to generate keypairs; I certainly use it for actual asymmetric encryption of data.)

**Comment by coolaj86** [comment]
@delfuego Is there a reason that `crypto.publicEncrypt(key, buffer)` and `crypto.privateDecrypt(privateKey, buffer)` don't work for your use case?

**Comment by delfuego** [comment]
@coolaj86 Maybe because I'm a slight moron? I recall having looked and thinking that it wouldn't do what I needed it to — but sure enough, `crypto` is perfectly adequate for what I need. Well, **most** of what I need; it doesn't appear to be able to give me the bit length of a public key, so I can't warn someone if they're about to try to encrypt something that's too long for the given key. But I'll be OK with what it can do for now!

Thanks.

**Comment by coolaj86** [comment]
@delfuego I took on the task of writing a complete PEM-to-JWK and JWK-to-PEM solution from scratch (0 dependencies, great tests, only about 550 lines of code (sans comments and newlines) using node's native RSA support, which you could use to get the length you need:

```js
'use strict';
var Rasha = require("rasha");

var pem = require('fs').readFileSync(process.argv[2], 'ascii');
var jwk = Rasha.importSync({ pem: pem });

console.log(Buffer.from(jwk.n, 'base64').byteLength);
```

Docs for [Rasha.js](https://git.coolaj86.com/coolaj86/rasha.js) at <https://git.coolaj86.com/coolaj86/rasha.js>

## Update: Node v10+ has Native RSA Support now

* `crypto.generateKeyPair()` 
  * https://nodejs.org/api/crypto.html#crypto_crypto_generatekeypair_type_options_callback
* `Rasha.generate()` (RSA + PEM<->JWK)
  * https://git.coolaj86.com/coolaj86/keypairs.js/
* `Keypairs.generate()` (RSA/ECDSA + PEM<->JWK)
  * https://git.coolaj86.com/coolaj86/rasha.js/

**Comment by jampy** [comment]
[![image](https://user-images.githubusercontent.com/820758/49802485-4cf16e00-fd4d-11e8-8feb-aa68617f2139.png)](https://www.npmjs.com/package/ursa)

**Comment by rzr** [comment]
hey @jampy check

https://github.com/JoshKaufman/ursa/issues/172

**Comment by loretoparisi** [comment]
This still happens in node LTS at current time:

```sh
> ursa@0.9.4 install /node_modules/ursa
> node-gyp rebuild

  CXX(target) Release/obj.target/ursaNative/src/ursaNative.o
../src/ursaNative.cc:389:13: error: member access into incomplete type 'RSA' (aka 'rsa_st')
    obj->rsa->n = BN_bin2bn(data_n, n_length, NULL);
            ^
/Users/loretoparisi/.node-gyp/10.1.0/include/node/openssl/ossl_typ.h:110:16: note: forward declaration of 'rsa_st'
typedef struct rsa_st RSA;
               ^
../src/ursaNative.cc:390:13: error: member access into incomplete type 'RSA' (aka 'rsa_st')
    obj->rsa->e = BN_bin2bn(data_e, e_length, NULL);
            ^
/Users/loretoparisi/.node-gyp/10.1.0/include/node/openssl/ossl_typ.h:110:16: note: forward declaration of 'rsa_st'
typedef struct rsa_st RSA;
               ^
../src/ursaNative.cc:407:35: error: member access into incomplete type 'RSA' (aka 'rsa_st')
    if ((obj == NULL) || (obj->rsa->d != NULL)) {
                                  ^
/Users/loretoparisi/.node-gyp/10.1.0/include/node/openssl/ossl_typ.h:110:16: note: forward declaration of 'rsa_st'
typedef struct rsa_st RSA;
               ^
../src/ursaNative.cc:536:34: error: member access into incomplete type 'RSA' (aka 'rsa_st')
    bignumToBuffer(args, obj->rsa->e);
                                 ^
/Users/loretoparisi/.node-gyp/10.1.0/include/node/openssl/ossl_typ.h:110:16: note: forward declaration of 'rsa_st'
typedef struct rsa_st RSA;
               ^
../src/ursaNative.cc:552:34: error: member access into incomplete type 'RSA' (aka 'rsa_st')
    bignumToBuffer(args, obj->rsa->d);
                                 ^
/Users/loretoparisi/.node-gyp/10.1.0/include/node/openssl/ossl_typ.h:110:16: note: forward declaration of 'rsa_st'
typedef struct rsa_st RSA;
               ^
../src/ursaNative.cc:567:34: error: member access into incomplete type 'RSA' (aka 'rsa_st')
    bignumToBuffer(args, obj->rsa->n);
                                 ^
/Users/loretoparisi/.node-gyp/10.1.0/include/node/openssl/ossl_typ.h:110:16: note: forward declaration of 'rsa_st'
typedef struct rsa_st RSA;
               ^
../src/ursaNative.cc:1218:17: error: member access into incomplete type 'RSA' (aka 'rsa_st')
        obj->rsa->n = modulus;
                ^
/Users/loretoparisi/.node-gyp/10.1.0/include/node/openssl/ossl_typ.h:110:16: note: forward declaration of 'rsa_st'
typedef struct rsa_st RSA;
               ^
../src/ursaNative.cc:1219:17: error: member access into incomplete type 'RSA' (aka 'rsa_st')
        obj->rsa->e = exponent;
                ^
/Users/loretoparisi/.node-gyp/10.1.0/include/node/openssl/ossl_typ.h:110:16: note: forward declaration of 'rsa_st'
typedef struct rsa_st RSA;
               ^
../src/ursaNative.cc:1220:17: error: member access into incomplete type 'RSA' (aka 'rsa_st')
        obj->rsa->p = p;
                ^
/Users/loretoparisi/.node-gyp/10.1.0/include/node/openssl/ossl_typ.h:110:16: note: forward declaration of 'rsa_st'
typedef struct rsa_st RSA;
               ^
../src/ursaNative.cc:1221:17: error: member access into incomplete type 'RSA' (aka 'rsa_st')
        obj->rsa->q = q;
                ^
/Users/loretoparisi/.node-gyp/10.1.0/include/node/openssl/ossl_typ.h:110:16: note: forward declaration of 'rsa_st'
typedef struct rsa_st RSA;
               ^
../src/ursaNative.cc:1222:17: error: member access into incomplete type 'RSA' (aka 'rsa_st')
        obj->rsa->dmp1 = dp;
                ^
/Users/loretoparisi/.node-gyp/10.1.0/include/node/openssl/ossl_typ.h:110:16: note: forward declaration of 'rsa_st'
typedef struct rsa_st RSA;
               ^
../src/ursaNative.cc:1223:17: error: member access into incomplete type 'RSA' (aka 'rsa_st')
        obj->rsa->dmq1 = dq;
                ^
/Users/loretoparisi/.node-gyp/10.1.0/include/node/openssl/ossl_typ.h:110:16: note: forward declaration of 'rsa_st'
typedef struct rsa_st RSA;
               ^
../src/ursaNative.cc:1224:17: error: member access into incomplete type 'RSA' (aka 'rsa_st')
        obj->rsa->iqmp = inverseQ;
                ^
/Users/loretoparisi/.node-gyp/10.1.0/include/node/openssl/ossl_typ.h:110:16: note: forward declaration of 'rsa_st'
typedef struct rsa_st RSA;
               ^
../src/ursaNative.cc:1225:17: error: member access into incomplete type 'RSA' (aka 'rsa_st')
        obj->rsa->d = d;
                ^
/Users/loretoparisi/.node-gyp/10.1.0/include/node/openssl/ossl_typ.h:110:16: note: forward declaration of 'rsa_st'
typedef struct rsa_st RSA;
               ^
../src/ursaNative.cc:1270:17: error: member access into incomplete type 'RSA' (aka 'rsa_st')
        obj->rsa->n = modulus;
                ^
/Users/loretoparisi/.node-gyp/10.1.0/include/node/openssl/ossl_typ.h:110:16: note: forward declaration of 'rsa_st'
typedef struct rsa_st RSA;
               ^
../src/ursaNative.cc:1271:17: error: member access into incomplete type 'RSA' (aka 'rsa_st')
        obj->rsa->e = exponent;
                ^
/Users/loretoparisi/.node-gyp/10.1.0/include/node/openssl/ossl_typ.h:110:16: note: forward declaration of 'rsa_st'
typedef struct rsa_st RSA;
               ^
16 errors generated.
make: *** [Release/obj.target/ursaNative/src/ursaNative.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:235:12)
gyp ERR! System Darwin 18.2.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /node_modules/ursa
gyp ERR! node -v v10.1.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 

```

**Comment by coolaj86** [comment]
@loretoparisi 

## Node v10+ has Native RSA Support now

* `crypto.generateKeyPair()` 
  * https://nodejs.org/api/crypto.html#crypto_crypto_generatekeypair_type_options_callback
* `Rasha.generate()` (RSA + PEM<->JWK)
  * https://git.coolaj86.com/coolaj86/keypairs.js/
* `Keypairs.generate()` (RSA/ECDSA + PEM<->JWK)
  * https://git.coolaj86.com/coolaj86/rasha.js/

**Comment by loretoparisi** [comment]
@solderjs thanks a lot!

**Comment by exallon72** [comment]
Hi I can't get crypto or Node-RSA to work as replacements for ursa. I have adapted the code but still no succes.

As you can see from the commented code ursa.createPublicKey and key.encrypt (ursa) does not seem to yield the same results. URSA is using the commented out base64 auth. I have of course tried with that also on both crypto and Node-RSA. Does anyone have any input on how to convert this?

`function encryptLogin(user, pass, keyfile) {
  var rsaPublic = fs.readFileSync(keyfile, 'ascii');
  //var key = ursa.createPublicKey(rsaPublic, 'utf8');
  const key = new NodeRSA(rsaPublic);
  
 // var key = rsaPublic.toString('utf8');
  if (!key) {
    console.log('KEY error');
  }

  // var auth = new Buffer(user).toString('base64');
  // auth += ':';
  // auth += new Buffer(pass).toString('base64');
  // auth += ':';
  // auth += new Buffer('' + new Date().getTime()).toString('base64');

  var auth = user;
  auth += ':';
  auth += pass;
  auth += ':';
  auth += new Date().getTime();
  //const loginKey = crypto.publicEncrypt({key: key, padding: crypto.constants.RSA_PKCS1_PADDING}, Buffer.from(auth));
  const encrypted = key.encrypt(Buffer.from(auth, 'base64'), 'base64', 'utf8');
  return encrypted.toString('base64');
  //return key.encrypt(auth, 'utf8', 'base64', ursa.RSA_PKCS1_PADDING);
}`
